services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pos
      POSTGRES_PASSWORD: pos
      POSTGRES_DB: pos
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pos"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=pos;Username=pos;Password=pos;Include Error Detail=true"
      Jwt__SigningKey: "compose_dev_signing_key_change_in_prod_xxxxx"
    depends_on:
      postgres: { condition: service_healthy }
      redis:    { condition: service_healthy }
    ports: ["8080:8080"]

  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.web
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ReverseProxy__Clusters__api__Destinations__primary__Address: "http://api:8080/"
    depends_on:
      api: { condition: service_started }
    ports: ["8081:8081"]

volumes:
  pgdata:
